// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJsDM0l3Bngc96ugyAPvncKOqUenALc5o',
    appId: '1:618037220000:web:6a1351451db2f8b24a2fc5',
    messagingSenderId: '618037220000',
    projectId: 'sett-451',
    authDomain: 'sett-451.firebaseapp.com',
    storageBucket: 'sett-451.firebasestorage.app',
    measurementId: 'G-HRQVV927GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRg0cdp9ZBy2wYooubvslzNYQFLdrUlM4',
    appId: '1:618037220000:android:228d9be26d0a005c4a2fc5',
    messagingSenderId: '618037220000',
    projectId: 'sett-451',
    storageBucket: 'sett-451.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0hdFb-p8GnTylBM-nrdRu_lZ0tm9dV9o',
    appId: '1:618037220000:ios:ea22eb2659d73b3b4a2fc5',
    messagingSenderId: '618037220000',
    projectId: 'sett-451',
    storageBucket: 'sett-451.firebasestorage.app',
    iosBundleId: 'com.example.setdeneme1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0hdFb-p8GnTylBM-nrdRu_lZ0tm9dV9o',
    appId: '1:618037220000:ios:ea22eb2659d73b3b4a2fc5',
    messagingSenderId: '618037220000',
    projectId: 'sett-451',
    storageBucket: 'sett-451.firebasestorage.app',
    iosBundleId: 'com.example.setdeneme1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJsDM0l3Bngc96ugyAPvncKOqUenALc5o',
    appId: '1:618037220000:web:7e58741d1f8d71314a2fc5',
    messagingSenderId: '618037220000',
    projectId: 'sett-451',
    authDomain: 'sett-451.firebaseapp.com',
    storageBucket: 'sett-451.firebasestorage.app',
    measurementId: 'G-8NCVHNV9XV',
  );
}
